artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/tentotheminus9/seti-data
  data_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.keras

model_evaluation:
  dagshub_uri: https://dagshub.com/bhuvaneshprasad/End-to-End-SETI-Classification-using-CNN-MLFlow-DVC.mlflow
  